#!/usr/bin/python
#-*- coding=utf-8 -*-

warning_dict = {
            "file_not_exist": {
                "zh_cn": "错误：文件不存在",
                "en_us": "Error: file not exist",
                "ig_ng": "aṣiṣe:faili ko tẹlẹ",
                "en_jm": "error:file nah exist",
                "ca_es": "error:archivo no existe",
                "pt_pt": "erro:arquivo não existe",
            },
            "wrong_file_type": {
                "zh_cn": "错误：不是Python源码文件",
                "en_us": "Error: not a Python source code file",
                "ig_ng": "Error: not a Python source code file",
                "en_jm": "Error: nah ah pydon source code file",
                "ca_es": "Error: no es un archivo de código fuente de Python",
                "pt_pt": "Erro: Não é um arquivo de código-fonte Python",
            },
            "syntax_error": {
                "zh_cn": "错误：语法错误\n文件 \"%s\", 第%d行\n\t",
                "en_us": "Error: syntax error\nFile \"%s\", line %d\n\t",
                "ig_ng": "Error: sintasi aṣiṣe faili\nFile \"%s\", line %d\n\t",
                "en_jm": "Error: Syntax error file\nFile \"%s\", line %d\n\t",
                "ca_es": "Error: Error de sintaxis archivo\nFile \"%s\", line %d\n\t",
                "pt_pt": "Erro: Erro de sintaxe arquivo\nFile \"%s\", line %d\n\t",
            },
            "parse_error": {
                "zh_cn": "错误：解析错误",
                "en_us": "Error: parsing error",
                "ig_ng": "Error: Ajọ faili",
                "en_jm": "Error: parsing error",
                "ca_es": "Error: análisis error",
                "pt_pt": "Erro: análise erro",
            },
            "generate_error": {
                "zh_cn": "错误：生成错误",
                "en_us": "Error: generating error",
                "ig_ng": "Error: ti o npese faili",
                "en_jm": "Error: generating error",
                "ca_es": "Error: Generación error",
                "pt_pt": "Erro: Gerando erro",
            },
        }

help_dict = {
            "file": {
                "zh_cn": "文件名",
                "en_us": "filename",
                "ig_ng": "orukọ faili",
                "en_jm": "filename",
                "ca_es": "nombre del archivo",
                "pt_pt": "nome do arquivo",
            },
            "output": {
                "zh_cn": "输出目录（不存在会被创建）",
                "en_us": "output directory(will be created if not exist)",
                "ig_ng": "o wu liana ( ti o ba ti yoo wa ni da ko tẹlẹ )",
                "en_jm": "output directory(will be created ef nah exist)",
                "ca_es": "directorio de salida (se creará si no existe)",
                "pt_pt": "o wu liana (ti o ba ti yoo wa ni da Tele ko)",
            },
            "encoding": {
                "zh_cn": "编码",
                "en_us": "encoding",
                "ig_ng": "aiyipada",
                "en_jm": "encoding",
                "ca_es": "codificación",
                "pt_pt": "codificação",
            },
        }

doc_dict = {
            "_title": {
                "zh_cn": "生成的文档",
                "en_us": "Documentation",
                "ig_ng": "Documentation",
                "en_jm": "Documentation",
                "ca_es": "Documentación",
                "pt_pt": "Documentação",
            },
            "_class": {
                "zh_cn": "类",
                "en_us": "Class",
                "ig_ng": "kilasi",
                "en_jm": "class",
                "ca_es": "clase",
                "pt_pt": "aula",
            },
            "_function": {
                "zh_cn": "函数",
                "en_us": "Function",
                "ig_ng": "Išė",
                "en_jm": "Function",
                "ca_es": "Función",
                "pt_pt": "Função",
            },
            "_method": {
                "zh_cn": "方法",
                "en_us": "Method",
                "ig_ng": "Method",
                "en_jm": "Medod",
                "ca_es": "Método",
                "pt_pt": "Método",
            },
            "_function": {
                "zh_cn": "函数",
                "en_us": "Function",
                "ig_ng": "Išė",
                "en_jm": "Function",
                "ca_es": "Función",
                "pt_pt": "Função",
            },
            "_cons": {
                "zh_cn": "构造器",
                "en_us": "Constructor",
                "ig_ng": "Constructor",
                "en_jm": "Constructor",
                "ca_es": "Constructor",
                "pt_pt": "Constructor",
            },
            "_method_general": {
                "zh_cn": "方法概要",
                "en_us": "Method Summary",
                "ig_ng": "Method ìla",
                "en_jm": "Medod Outline",
                "ca_es": "Método Contorno",
                "pt_pt": "Método Esboço",
            },
            "_function_general": {
                "zh_cn": "函数概要",
                "en_us": "Function Summary",
                "ig_ng": "Išė ìla",
                "en_jm": "Function Outline",
                "ca_es": "Función Contorno",
                "pt_pt": "Função Esboço",
            },
            "_method_details": {
                "zh_cn": "方法详细资料",
                "en_us": "Method Details",
                "ig_ng": "Method Awọn alaye",
                "en_jm": "Medod Details",
                "ca_es": "Método Detalles",
                "pt_pt": "Método Detalhes",
            },
            "_function_details": {
                "zh_cn": "函数概要",
                "en_us": "Function Details",
                "ig_ng": "Išė Awọn alaye",
                "en_jm": "Function Details",
                "ca_es": "Función Detalles",
                "pt_pt": "Função Detalhes",
            },
            "_cons_general": {
                "zh_cn": "构造器概要",
                "en_us": "Constructor Summary",
                "ig_ng": "Constructor ìla",
                "en_jm": "Constructor Outline",
                "ca_es": "Constructor Contorno",
                "pt_pt": "Constructor Esboço",
            },
            "_cons_details": {
                "zh_cn": "构造器详细资料",
                "en_us": "Constructor Details",
                "ig_ng": "Constructor Awọn alaye",
                "en_jm": "Constructor Details",
                "ca_es": "Constructor Detalles",
                "pt_pt": "Constructor Detalhes",
            },
            "_method_general_table": {
                "zh_cn": "方法概要表",
                "en_us": "Method Summary Table",
                "ig_ng": "Method ìla Table",
                "en_jm": "Medod Outline Table",
                "ca_es": "Método Contorno Table",
                "pt_pt": "Método Esboço Table",
            },
            "_function_general_table": {
                "zh_cn": "函数概要表",
                "en_us": "Function Summary Table",
                "ig_ng": "Išė ìla Table",
                "en_jm": "Function Outline Table",
                "ca_es": "Función Contorno Table",
                "pt_pt": "Função Esboço Table",
            },
            "_cons_general_table": {
                "zh_cn": "构造器概要表",
                "en_us": "Constructor Summary Table",
                "ig_ng": "Constructor ìla Table",
                "en_jm": "Constructor Outline Table",
                "ca_es": "Constructor Contorno Table",
                "pt_pt": "Constructor Esboço Table",
            },
            "_all_files": {
                "zh_cn": "全部文件",
                "en_us": "All Files",
                "ig_ng": "All Faili",
                "en_jm": "All File",
                "ca_es": "All Archivo",
                "pt_pt": "All Arquivo",
            },
            "_file": {
                "zh_cn": "文件",
                "en_us": "File",
                "ig_ng": "Faili",
                "en_jm": "File",
                "ca_es": "Archivo",
                "pt_pt": "Arquive"
            },

            # tags
            "_throws": {
                "zh_cn": "抛出",
                "en_us": "Throws",
                "ig_ng": "Ju",
                "en_jm": "Drows",
                "ca_es": "Lanza",
                "pt_pt": "Lança",
            },
            "_return": {
                "zh_cn": "返回",
                "en_us": "Returns",
                "ig_ng": "Padà",
                "en_jm": "Returns",
                "ca_es": "Devoluciones",
                "pt_pt": "Devoluções",
            },
            "_param": {
                "zh_cn": "参数",
                "en_us": "Parameters",
                "ig_ng": "Igbeseô",
                "en_jm": "Parameter",
                "ca_es": "Parámetro",
                "pt_pt": "Parâmetro",
            },
            "_author": {
                "zh_cn": "作者",
                "en_us": "Author",
                "ig_ng": "Onkowe",
                "en_jm": "Audor",
                "ca_es": "Autor",
                "pt_pt": "Autor",
            },
            "_version": {
                "zh_cn": "版本",
                "en_us": "Version",
                "ig_ng": "Version",
                "en_jm": "Version",
                "ca_es": "Versión",
                "pt_pt": "versão",
            },
            "_since": {
                "zh_cn": "自从",
                "en_us": "Version",
                "ig_ng": "Niwon",
                "en_jm": "Since",
                "ca_es": "Desde",
                "pt_pt": "Desde",
            },
            "_demostration": {
                "zh_cn": "说明",
                "en_us": "Demostration",
                "ig_ng": "Demostration",
                "en_jm": "Demostration",
                "ca_es": "Demostration",
                "pt_pt": "Demostration",
            },
            "_file_annotation": {
                "zh_cn": "文件注释",
                "en_us": "File Annotation",
                "ig_ng": "Faili Annotation",
                "en_jm": "File Annotation",
                "ca_es": "Nombre Annotation",
                "pt_pt": "Nome Annotation",
            },
            "_package": {
                "zh_cn": "程序包",
                "en_us": "Package",
                "ig_ng": "Eto Package",
                "en_jm": "Package",
                "ca_es": "Paquete De Programas",
                "pt_pt": "Pacote De Programa",
            },
        }
